public class InitializationData extends Information implements InitializationdataInterface{
    @Override
    public void ProvidingAndFilling(Information information) {
        getNicknameList().add("username1");
        getNicknameList().add("username2");
        getNicknameList().add("username3");
        getNicknameList().add("username4");
        getNicknameList().add("username5");
        getNicknameList().add("username6");
        getNicknameList().add("username7");
        getNicknameList().add("username8");
        getNicknameList().add("username9");
        getNicknameList().add("username10");
        getNicknameList().add("username11");
        getNicknameList().add("username12");
        getNicknameList().add("username13");
        getNicknameList().add("username14");
        getNicknameList().add("username15");
        getNicknameList().add("username16");
        getNicknameList().add("username17");
        getNicknameList().add("username18");
        getNicknameList().add("username19");
        getNicknameList().add("username20");
        getNicknameList().add("username21");
        getNicknameList().add("username22");
        getNicknameList().add("username23");
        getNicknameList().add("username24");
        getNicknameList().add("username25");
        getNicknameList().add("username26");
        getNicknameList().add("username27");
        getNicknameList().add("username28");
        getNicknameList().add("username29");
        getNicknameList().add("username30");

        getUserMailSet().add("Mail1@gmail.com");
        getUserMailSet().add("Mail2@gmail.com");
        getUserMailSet().add("Mail3@gmail.com");
        getUserMailSet().add("Mail4@gmail.com");
        getUserMailSet().add("Mail5@gmail.com");
        getUserMailSet().add("Mail6@gmail.com");
        getUserMailSet().add("Mail7@gmail.com");
        getUserMailSet().add("Mail8@gmail.com");
        getUserMailSet().add("Mail9@gmail.com");
        getUserMailSet().add("Mail10@gmail.com");
        getUserMailSet().add("Mail11@gmail.com");
        getUserMailSet().add("Mail12@gmail.com");
        getUserMailSet().add("Mail13@gmail.com");
        getUserMailSet().add("Mail14@gmail.com");
        getUserMailSet().add("Mail15@gmail.com");
        getUserMailSet().add("Mail16@gmail.com");
        getUserMailSet().add("Mail17@gmail.com");
        getUserMailSet().add("Mail18@gmail.com");
        getUserMailSet().add("Mail19@gmail.com");
        getUserMailSet().add("Mail20@gmail.com");
        getUserMailSet().add("Mail21@gmail.com");
        getUserMailSet().add("Mail22@gmail.com");
        getUserMailSet().add("Mail23@gmail.com");
        getUserMailSet().add("Mail24@gmail.com");
        getUserMailSet().add("Mail25@gmail.com");
        getUserMailSet().add("Mail26@gmail.com");
        getUserMailSet().add("Mail27@gmail.com");
        getUserMailSet().add("Mail28@gmail.com");
        getUserMailSet().add("Mail29@gmail.com");
        getUserMailSet().add("Mail30@gmail.com");

        getRatioUserMailMap().put("mail1@ukr.net", "user1");
        getRatioUserMailMap().put("mail2@ukr.net", "user2");
        getRatioUserMailMap().put("mail3@ukr.net", "user3");
        getRatioUserMailMap().put("mail4@ukr.net", "user4");
        getRatioUserMailMap().put("mail5@ukr.net", "user5");
        getRatioUserMailMap().put("mail6@ukr.net", "user6");
        getRatioUserMailMap().put("mail7@ukr.net", "user7");
        getRatioUserMailMap().put("mail8@ukr.net", "user8");
        getRatioUserMailMap().put("mail9@ukr.net", "user9");
        getRatioUserMailMap().put("mail10@ukr.net", "user10");
        getRatioUserMailMap().put("mail11@ukr.net", "user11");
        getRatioUserMailMap().put("mail12@ukr.net", "user12");
        getRatioUserMailMap().put("mail13@ukr.net", "user13");
        getRatioUserMailMap().put("mail14@ukr.net", "user14");
        getRatioUserMailMap().put("mail15@ukr.net", "user15");
        getRatioUserMailMap().put("mail16@ukr.net", "user16");
        getRatioUserMailMap().put("mail17@ukr.net", "user17");
        getRatioUserMailMap().put("mail18@ukr.net", "user18");
        getRatioUserMailMap().put("mail19@ukr.net", "user19");
        getRatioUserMailMap().put("mail20@ukr.net", "user20");
        getRatioUserMailMap().put("mail21@ukr.net", "user21");
        getRatioUserMailMap().put("mail22@ukr.net", "user22");
        getRatioUserMailMap().put("mail23@ukr.net", "user23");
        getRatioUserMailMap().put("mail24@ukr.net", "user24");
        getRatioUserMailMap().put("mail25@ukr.net", "user25");
        getRatioUserMailMap().put("mail26@ukr.net", "user26");
        getRatioUserMailMap().put("mail27@ukr.net", "user27");
        getRatioUserMailMap().put("mail28@ukr.net", "user28");
        getRatioUserMailMap().put("mail29@ukr.net", "user29");
        getRatioUserMailMap().put("mail30@ukr.net", "user30");

        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");
        getNicknameList().add("sameUserName");

        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");
        getUserMailSet().add("sameMail@gmail.com");

        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");
        getRatioUserMailMap().put("sameMail@ukr.net", "sameUser");

        return ;
    }
}
